import {Database} from "./database/types.js";

type ItemType = Database['public']['Enums']['item_type'] // 'business' | 'resource' | 'event'

export type SeedType = {
    id: number
    typeName: string
    item_type: ItemType
    tags: { id: number; name: string; }[]
}

export type SeedAudience = {
    id: number
    typeName: string
    tags: { id: number; name: string; }[]
}

export const EVENT_SEED_TYPES_TAGS: SeedType[] = [
    {
        id: 0,
        typeName: 'Pride & Seasonal',
        item_type: 'event',
        tags: [
            { id: 1, name: 'Pride Parades & Festivals' },
            { id: 2, name: 'Queer Holiday Events' },
            { id: 3, name: 'Coming Out Day Celebrations' },
            { id: 4, name: 'Queer Prom & Costume Parties' },
            { id: 5, name: 'Youth Prom' },
            { id: 6, name: 'Elder Prom' },
            { id: 7, name: 'Pride March' },
            { id: 8, name: 'Pride Rally' },
            { id: 9, name: 'Pride Block Party' },
            { id: 10, name: 'Pride Boat Cruise' },
            { id: 11, name: 'Pride History' },
            { id: 12, name: 'Flag Raising' },
            { id: 13, name: 'World Pride' },
            { id: 14, name: 'Pride Kick Off' },
            { id: 15, name: 'Official Pride Party' },
            { id: 16, name: 'Pride Festival Packages' },
        ],
    },
    {
        id: 1,
        typeName: 'Identity-Specific Spaces',
        item_type: 'event',
        tags: [
            { id: 17, name: '2SLGBTQIA+' },
            { id: 18, name: 'Queer-Affirming Spaces' },
            { id: 19, name: 'Trans & Nonbinary' },
            { id: 20, name: 'Lesbian, Bi, & WLW' },
            { id: 21, name: 'Gay, Bi, & MLM' },
            { id: 22, name: 'Asexual & Aromantic Gatherings' },
            { id: 23, name: 'Two-Spirit & Indigenous Spaces' },
        ],
    },
    {
        id: 2,
        typeName: 'Socials & Nightlife',
        item_type: 'event',
        tags: [
            { id: 24, name: 'Club Nights & Dance Parties' },
            { id: 25, name: 'Queer Bars & Theme Nights' },
            { id: 26, name: 'Drag Brunch & Tea Parties' },
            { id: 27, name: 'Leather & Kink Events' },
            { id: 28, name: 'Pride After Parties & After-Hours' },
            { id: 29, name: 'Sober & Low-Sensory Events' },
            { id: 30, name: 'Open Mics, Trivia & Karaoke' },
            { id: 31, name: 'Queer DJ Sets & Raves' },
            { id: 32, name: 'Fetish & Underground Events' },
            { id: 33, name: 'Pop Up Events' },
            { id: 34, name: 'Clothing Swap / Drive' },
            { id: 288, name: 'Cocktails & Happy Hours' },
            { id: 35, name: 'Drag/Bingo' },
        ],
    },
    {
        id: 3,
        typeName: 'Arts, Music & Performance',
        item_type: 'event',
        tags: [
            { id: 36, name: 'Queer Live Music' },
            { id: 37, name: 'Spoken Word & Poetry Slams' },
            { id: 38, name: 'Drag Shows & Cabarets' },
            { id: 39, name: 'Queer Film Screenings & Festivals' },
            { id: 40, name: 'Gallery Openings & Art Shows' },
            { id: 41, name: 'Book Readings' },
            { id: 42, name: 'Arts & Crafts Events' },
            { id: 43, name: "Q&A’s + Discussions" },
            { id: 289, name: "Queer / Comedy Shoes & Open Mics" },
            { id: 290, name: "Karaoke Trivia & Game Nights" },
        ],
    },
    {
        id: 4,
        typeName: 'Community & Culture',
        item_type: 'event',
        tags: [
            { id: 44, name: 'Meetups & Mixers' },
            { id: 45, name: 'Drag & Ballroom Events' },
            { id: 46, name: '2SLGBTQIA+ History & Heritage' },
            { id: 47, name: 'Intergenerational Gatherings' },
            { id: 48, name: 'QTPOC Events' },
            { id: 49, name: 'Fundraisers & Galas' },
        ],
    },
    {
        id: 5,
        typeName: 'Friends & Family',
        item_type: 'event',
        tags: [
            { id: 50, name: 'Family Acceptance Workshops' },
            { id: 51, name: 'PFLAG Meetings' },
            { id: 52, name: 'Queer 101 for Families' },
            { id: 53, name: 'Community Dinners / Potlucks' },
            { id: 54, name: 'Ally Training Sessions' },
            { id: 55, name: 'Support Circles for Parents/Guardians' },
        ],
    },
    {
        id: 6,
        typeName: 'Health & Wellness',
        item_type: 'event',
        tags: [
            { id: 56, name: 'Mental Health Circles' },
            { id: 57, name: 'Peer Support Groups' },
            { id: 58, name: 'Sexual Health Clinics & Info Sessions' },
            { id: 59, name: 'Yoga, Meditation & Movement' },
            { id: 60, name: 'Harm Reduction & Recovery Spaces' },
        ],
    },
    {
        id: 7,
        typeName: 'Resources & Services',
        item_type: 'event',
        tags: [
            { id: 61, name: 'Free Testing & Health Clinics' },
            { id: 62, name: 'Legal Aid & Name Change Clinics' },
            { id: 63, name: 'Mutual Aid Drives' },
            { id: 64, name: 'Housing & Shelter Access' },
            { id: 65, name: 'Therapy & Counseling Resources' },
        ],
    },
    {
        id: 8,
        typeName: 'Education & Workshops',
        item_type: 'event',
        tags: [
            { id: 66, name: 'Gender & Sexuality Workshops' },
            { id: 67, name: 'Sex Ed & Body Positivity' },
            { id: 68, name: 'Writing, Art & Creative Labs' },
            { id: 69, name: 'Legal Rights & Advocacy' },
            { id: 70, name: 'Financial Literacy' },
        ],
    },
    {
        id: 9,
        typeName: 'Religion & Spirituality',
        item_type: 'event',
        tags: [
            { id: 71, name: 'Queer-Affirming Worship Services' },
            { id: 72, name: '2SLGBTQIA+ Interfaith Gatherings' },
            { id: 73, name: 'Trans & Queer Healing Circles' },
            { id: 74, name: 'Religious Trauma Support Groups' },
            { id: 75, name: 'Pride Shabbat, Queer Seder, Queer Eid' },
            { id: 76, name: 'Faith-Based Ally Trainings' },
            { id: 77, name: '2SLGBTQIA+ Faith & Justice Panels' },
            { id: 78, name: 'Meditation, Prayer & Reflection Spaces' },
            { id: 79, name: 'Queer Clergy-Led Ceremonies' },
            { id: 80, name: 'Inc.lusive Faith Community Events' },
        ],
    },
    {
        id: 10,
        typeName: 'Business & Career',
        item_type: 'event',
        tags: [
            { id: 81, name: 'Queer-Owned Business Markets' },
            { id: 82, name: '2SLGBTQIA+ Professional Networking' },
            { id: 83, name: 'Job Fairs & Hiring Events' },
            { id: 84, name: 'Pitch Nights & Start-Up Showcases' },
            { id: 85, name: 'Vendor & Volunteer Registration' },
            { id: 86, name: 'DEI Trainings & Panels' },
        ],
    },
    {
        id: 11,
        typeName: 'Sports & Recreation',
        item_type: 'event',
        tags: [
            { id: 87, name: 'Queer Sports Tournaments' },
            { id: 88, name: '2SLGBTQIA+ Rec Leagues' },
            { id: 89, name: 'Pride Runs, Walks & Races' },
            { id: 90, name: 'Open Gym & Pickup Games' },
            { id: 91, name: 'Queer Hikes & Outdoor Adventures' },
            { id: 92, name: 'Inc.lusive Fitness Classes' },
            { id: 93, name: 'Roller Skating Nights' },
            { id: 94, name: 'Queer Bike Rides' },
            { id: 95, name: 'Pool Parties & Swim Meets' },
            { id: 96, name: 'Trans-Inclusive Athletics' },
        ],
    },
]

export const BUSINESS_SEED_TYPES_AND_TAGS: SeedType[] = [
    {
        id: 12,
        typeName: 'Arts & Culture',
        item_type: 'business',
        tags: [
            { id: 97, name: 'Artist Studios & Open-Work Spaces' },
            { id: 98, name: 'Cultural Festivals' },
            { id: 99, name: 'Fringe & Experimental Arts Spaces' },
            { id: 100, name: 'Local Art Fairs & Gallery Districts' },
            { id: 101, name: 'Performing Arts Venues' },
            { id: 102, name: 'Queer Craft Zine & Comic Creators' },
            { id: 103, name: 'Queer Film & Independent Cinemas' },
            { id: 104, name: 'Queer Literary Spaces & Poetry Venues' },
            { id: 105, name: 'Queer Playwrights Actors & Ensembles' },
            { id: 106, name: 'Musicians, Dancers & Visual Artists/ Performers' },
        ],

    },
    {
        id: 13,
        typeName: 'Attractions & Activities',
        item_type: 'business',
        tags: [
            { id: 107, name: 'Architectural Sites & City Icons' },
            { id: 108, name: 'Botanical Gardens & Conservatories' },
            { id: 109, name: 'Community Cultural Centers' },
            { id: 110, name: 'Interactive Science & Discovery Centers' },
            { id: 111, name: 'LGBTQ+ Heritage Walks & Monuments' },
            { id: 112, name: 'Museums' },
            { id: 113, name: 'Murals & Queer Street Art' },
            { id: 114, name: 'Observatories & Planetariums' },
            { id: 115, name: 'Public Art Installations & Sculptures' },
            { id: 116, name: 'Queer Landmarks & Historic Sites' },
            { id: 117, name: 'Zoos & Aquariums' },
        ],
    },
    {
        id: 14,
        typeName: 'Community Nonprofit & Public Services',
        item_type: 'business',
        tags: [
            { id: 118, name: 'Queer Community Events/Venues' },
            { id: 119, name: 'Cultural Offices' },
            { id: 120, name: 'Legal Aid & LGBTQ+ Rights Firms (For-Profit)' },
            { id: 121, name: 'Local Government LGBTQ+ Liaisons (Third-Party)' },
            { id: 122, name: 'Mediation & Conflict Resolution Services' },
            { id: 123, name: 'Private Security & Community Safety Firms' },
            { id: 124, name: 'Professional Training & Certification Providers' },
            { id: 125, name: 'Tourism Boards (Private / For-Profit Tourism Offices)' },
        ],
    },
    {
        id: 15,
        typeName: 'Family, Kids & Education',
        item_type: 'business',
        tags: [
            { id: 126, name: 'Family Resource Centers' },
            { id: 127, name: 'Family-Friendly Cafés & Bakeries' },
            { id: 128, name: 'Inclusive Clothing & Gift Boutiques' },
            { id: 129, name: 'Kid-Inclusive Fitness & Recreation Studios' },
            { id: 130, name: 'LGBTQ+ Event Planners' },
            { id: 131, name: 'LGBTQ+ Family Photographers' },
            { id: 132, name: 'LGBTQ+ Parenting Programs' },
            { id: 133, name: 'Queer-Friendly Arcades Mini Golf & Play Spaces' },
            { id: 134, name: 'Queer-Owned Childcare & Babysitting' },
            { id: 135, name: 'Queer-Owned Toy & Book Shops' },
            { id: 136, name: 'Tutoring Centers & Educational Supply Shops' },
            { id: 137, name: 'Youth Arts & Creative Workshops' },
        ],
    },
    {
        id: 16,
        typeName: 'Food & Drink',
        item_type: 'business',
        tags: [
            { id: 138, name: 'Bakeries & Dessert Shops' },
            { id: 139, name: 'Breweries Pubs & Lounges' },
            { id: 140, name: 'Cocktail Bars & Lounges' },
            { id: 141, name: 'Food Co-ops & Community Kitchens' },
            { id: 142, name: 'Food Trucks & Pop-Ups' },
            { id: 143, name: 'Queer Cafés & Coffeehouses' },
            { id: 144, name: 'Queer Caterers & Private Chefs' },
            { id: 145, name: 'Queer-Owned / Grocery & Market Stalls' },
            { id: 146, name: 'Queer-Owned / Restaurants & Diners' },
            { id: 147, name: 'Specialty Food Shops' },
            { id: 148, name: 'Vegan & Vegetarian Spots' },
            { id: 149, name: 'Wine Bars & Tasting Rooms' },
            { id: 150, name: 'Clubs & Clubhouses' },
        ],
    },
    {
        id: 17,
        typeName: 'Health, Beauty & Wellness',
        item_type: 'business',
        tags: [
            { id: 151, name: 'Barbershops & Grooming Studios' },
            { id: 152, name: 'Holistic & Alternative Medicine' },
            { id: 153, name: 'LGBTQ+ Health Clinics & Practices' },
            { id: 154, name: 'Massage & Bodywork Practices' },
            { id: 155, name: 'Meditation & Mindfulness Centers' },
            { id: 156, name: 'Mental Health Providers' },
            { id: 157, name: 'Queer-Affirming / Spas & Salons' },
            { id: 158, name: 'Queer-Friendly Gyms' },
            { id: 159, name: 'Sexual Health & Wellness Clinics' },
            { id: 160, name: 'Tattoo & Piercing Studios' },
            { id: 161, name: 'Voice Coaching & Gender-Affirming Services' },
            { id: 162, name: 'Yoga Dance & Fitness Studios' },
        ],
    },
    {
        id: 18,
        typeName: 'Home & Lifestyle Services',
        item_type: 'business',
        tags: [
            { id: 163, name: 'Cleaning Services' },
            { id: 164, name: 'Gardening & Landscaping' },
            { id: 165, name: 'Home Décor & Furniture Shops' },
            { id: 166, name: 'Movers & Hauling Services' },
            { id: 167, name: 'Real Estate Agents & Queer-Affirming Realtors' },
            { id: 168, name: 'Repair Services' },
        ],
    },
    {
        id: 19,
        typeName: 'Nightlife & Entertainment',
        item_type: 'business',
        tags: [
            { id: 169, name: 'Dance Clubs & Queer Nights' },
            { id: 170, name: 'Drag & Cabaret Performances / Venues' },
            { id: 171, name: 'Tea Dances & Pageants' },
            { id: 172, name: 'Boat & Cruise Parties' },
            { id: 173, name: 'Fetish Leather & Underground Events' },
            { id: 174, name: 'Immersive Queer Events & Alt Spaces' },
            { id: 175, name: 'Indie Theaters & Performance Spaces' },
            { id: 176, name: 'Karaoke Trivia & Game Nights' },
            { id: 177, name: 'Live Music Venues' },
            { id: 178, name: 'Pride & Festival Party Venues' },
            { id: 179, name: 'Queer / Bars & Taverns' },
            { id: 180, name: 'Queer / Comedy Shows & Open Mics' },
            { id: 181, name: 'Queer / DJ Sets & Raves' },
            { id: 182, name: 'Sober & Low-Sensory Nightlife' },
        ],
    },
    {
        id: 20,
        typeName: 'Outdoor & Recreation',
        item_type: 'business',
        tags: [
            { id: 183, name: 'Bike Paths & Cycling Routes' },
            { id: 184, name: 'Dog Parks & Pet-Friendly Spaces' },
            { id: 185, name: 'LGBTQ+ Camping & Outdoor Retreat Sites' },
            { id: 186, name: 'Nature Reserves & Wildlife Areas' },
            { id: 187, name: 'Parks & Green Spaces' },
            { id: 188, name: 'Public Pools & Recreation Centers' },
            { id: 189, name: 'Queer-Friendly Outdoor Adventure Groups' },
            { id: 190, name: 'Trailheads & Hiking Routes' },
            { id: 191, name: 'Waterfronts Beaches & Piers' },
            { id: 192, name: 'Boat Tours & Cruises' },
            { id: 193, name: 'Walks, Runs & Marathons' },
        ],
    },
    {
        id: 21,
        typeName: 'Professional & Creative Services',
        item_type: 'business',
        tags: [
            { id: 194, name: 'Networking & Mentorship' },
            { id: 195, name: 'Financial Services' },
            { id: 196, name: 'Co-Working & Office Spaces' },
            { id: 197, name: 'Design Studios' },
            { id: 198, name: 'Film Stage & Event Production' },
            { id: 199, name: 'HR DEI & Organizational Consulting' },
            { id: 200, name: 'Legal & Accounting Services' },
            { id: 201, name: 'Marketing Branding & PR Agencies' },
            { id: 202, name: 'Photography Videography & Creative Studios' },
            { id: 203, name: 'Print & Production Shops' },
            { id: 204, name: 'Queer-Owned Businesses' },
            { id: 205, name: 'Web Development & Tech Firms' },
        ],
    },
    {
        id: 22,
        typeName: 'Retail & Shopping',
        item_type: 'business',
        tags: [
            { id: 206, name: 'Adult Intimacy & Toy Shops' },
            { id: 207, name: 'Art Galleries & Queer Artist Collectives' },
            { id: 208, name: 'Craft Supply & Stationery Stores' },
            { id: 209, name: 'Fashion Boutiques & Apparel Shops' },
            { id: 210, name: 'Home Goods & Décor Shops' },
            { id: 211, name: 'Jewelry & Accessories Shops' },
            { id: 212, name: 'Makers Markets & Pop-Up Shops' },
            { id: 213, name: 'Plant Shops & LGBTQ+ Florists' },
            { id: 214, name: 'Queer-Owned Bookstores' },
            { id: 215, name: 'Record & Music Shops' },
            { id: 216, name: 'Specialty Retail' },
            { id: 217, name: 'Thrift Vintage & Consignment Stores' },
        ],
    },
    {
        id: 23,
        typeName: 'Travel, Tourism & Lodging',
        item_type: 'business',
        tags: [
            { id: 218, name: 'Accessible Transport Providers' },
            { id: 219, name: 'Airport Transfers & Rideshare Alternatives' },
            { id: 220, name: 'B&Bs & Guesthouses' },
            { id: 221, name: 'Bike Rentals Scooters & Micro-Mobility' },
            { id: 222, name: 'Boutique & Luxury Stays' },
            { id: 223, name: 'LGBTQ+ Campgrounds & Cabins' },
            { id: 224, name: 'LGBTQ+ Shuttle Services' },
            { id: 225, name: 'LGBTQ+ Tour Operators' },
            { id: 226, name: 'LGBTQ+ Travel Media' },
            { id: 227, name: 'Queer City Guides & Local Hosts' },
            { id: 228, name: 'Queer-Owned / Hotels & Hostels' },
            { id: 229, name: 'Queer-Owned Transportation' },
            { id: 230, name: 'Pride & Festival Travel Packages' },
            { id: 231, name: 'Short-Term Rentals' },
            { id: 232, name: 'Visitor Centers & Tourism Boards' },
        ],
    },
]

export const RESOURCE_SEED_TYPES_AND_TAGS: SeedType[] = [
    {
        id: 24,
        typeName: 'Community & Advocacy',
        item_type: 'resource',
        tags: [
            { id: 233, name: 'LGBTQ+ Community Centers' },
            { id: 234, name: 'Pride & Advocacy Organizations' },
            { id: 235, name: 'Youth & Student Programs' },
            { id: 236, name: 'Senior & Elder Queer Programs' },
            { id: 237, name: 'QTPOC Collectives' },
            { id: 238, name: 'Trans & Nonbinary Networks' },
            { id: 239, name: 'Lesbian / WLW Groups' },
            { id: 240, name: 'Gay / MLM Groups' },
            { id: 241, name: '2-Spirit & Indigenous Spaces' },
            { id: 242, name: 'Immigrant & Refugee Queer Support' },
        ],
    },
    {
        id: 25,
        typeName: 'Health & Wellness',
        item_type: 'resource',
        tags: [
            { id: 243, name: 'Mental Health Counseling & Therapy' },
            { id: 244, name: 'Peer Support Groups' },
            { id: 245, name: 'HIV Testing & PrEP Access' },
            { id: 246, name: 'STI Clinics & Sexual Health Services' },
            { id: 247, name: 'Gender-Affirming Care (HRT, Surgery, Voice, Hair Removal)' },
            { id: 248, name: 'Recovery & Harm Reduction Programs' },
            { id: 249, name: 'Disability-Inclusive Wellness' },
            { id: 250, name: 'Accessible Fitness & Recreation' },
        ],
    },
    {
        id: 26,
        typeName: 'Legal & Rights Support',
        item_type: 'resource',
        tags: [
            { id: 251, name: 'Legal Aid Clinics' },
            { id: 252, name: 'Name & ID Change Support' },
            { id: 253, name: 'Housing Rights & Tenant Advocacy' },
            { id: 254, name: 'Workplace Rights & Union Allies' },
            { id: 255, name: 'Immigration & Asylum Legal Support' },
            { id: 256, name: 'Anti-Discrimination & Civil Rights Services' },
        ],
    },
    {
        id: 27,
        typeName: 'Education & Learning',
        item_type: 'resource',
        tags: [
            { id: 257, name: 'Queer Libraries & Archives' },
            { id: 258, name: 'Queer History & Heritage Projects' },
            { id: 259, name: 'Workshops & Trainings (DEI, Allyship, Queer 101)' },
            { id: 260, name: 'Sex Ed & Body Positivity Programs' },
            { id: 261, name: 'University LGBTQ+ Groups' },
            { id: 262, name: 'Queer Art & Writing Labs' },
            { id: 263, name: 'Financial Literacy Workshops' },
        ],
    },
    {
        id: 28,
        typeName: 'Crisis & Safety Support',
        item_type: 'resource',
        tags: [
            { id: 264, name: 'Crisis Hotlines' },
            { id: 265, name: 'Suicide Prevention Services' },
            { id: 266, name: 'Domestic Violence Shelters' },
            { id: 267, name: 'Homeless Queer Youth Programs' },
            { id: 268, name: 'Family & Parent Acceptance Support' },
            { id: 269, name: 'Emergency Housing & Shelter Access' },
        ],
    },
    {
        id: 29,
        typeName: 'Faith & Spirituality',
        item_type: 'resource',
        tags: [
            { id: 270, name: 'Queer-Affirming Churches' },
            { id: 271, name: 'Inclusive Synagogues, Mosques & Temples' },
            { id: 272, name: 'Interfaith Queer Gatherings' },
            { id: 273, name: 'Religious Trauma Support' },
            { id: 274, name: 'Queer Ritual & Spiritual Circles' },
            { id: 275, name: 'Queer Clergy & Officiants' },
        ],
    },
    {
        id: 30,
        typeName: 'Social & Community Events',
        item_type: 'resource',
        tags: [
            { id: 276, name: 'Queer Sports Leagues & Recreation' },
            { id: 277, name: 'Outdoor & Adventure Groups' },
            { id: 278, name: 'Arts & Maker Collectives' },
            { id: 279, name: 'Book Clubs & Reading Groups' },
            { id: 280, name: 'Intergenerational Gatherings' },
            { id: 281, name: 'Social Meetups & Interest Groups' },
        ],
    },
    {
        id: 31,
        typeName: 'Practical Help & Services',
        item_type: 'resource',
        tags: [
            { id: 282, name: 'Food Pantries & Mutual Aid' },
            { id: 283, name: 'Housing Support Services' },
            { id: 284, name: 'Job Training & Career Navigation' },
            { id: 285, name: 'Queer Mentorship Programs' },
            { id: 286, name: 'Technology Access & Digital Literacy' },
            { id: 287, name: 'Trans & Nonbinary Resource Navigators' },
        ],
    },
]
